__name__ = "lsabe"
__version__ = "1.0.0"
__summary__ = "LSABE algorithm"
__uri__ = "https://github.com/maxirmx/LSABE"
__author__ = "Maxim Samsonov"
__email__ = "m.samsonov@computer.org"
__license__ = "MIT"